### ISSUE TITLE
Another new paper

### ISSUE THREAD

**Issue by zhangmozhe** [heejkoo/Awesome-Diffusion-Models#10]
Hi, thanks for making this great repo to track the recent awesome works. 

We have recently posted our paper to arXiv (https://arxiv.org/abs/2205.12952) with the webpage (https://tengfei-wang.github.io/PITI/index.html), which uses diffusion model for image-to-image translation. Could you please include this paper in the repo? 

Thanks!

**Comment by hee9joon** [comment]
The mentioned paper is already added. Thank you for your interest in this repo!

**Comment by zhangmozhe** [comment]
Thank you! The repo is great for the community!
