### ISSUE TITLE
New paper about scene graph-based diffusion model

### ISSUE THREAD

**Issue by YangLing0818** [heejkoo/Awesome-Diffusion-Models#44]
Hello, thanks for your great repo, it is really awesome. Recently we published our new paper "Diffusion-Based Scene Graph to Image Generation with Masked Contrastive Pre-Training" on arXiv, which proposes a diffusion model that directly conditions on scene graphs to generate images. Could you please add this paper to the repo? Thanks a lot!

arxiv: https://arxiv.org/abs/2211.11138
GitHub: https://github.com/YangLing0818/SGDiff

**Comment by heejkoo** [comment]
I will add it asap. Many remarkable papers on diffusion models have been published recently so there will be a slight delay in updating the repo. Thank you again for informing your paper!
