### ISSUE TITLE
Paper titled "Semantic Diffusion Network for Semantic Segmentation" is not actually a Diffusion based Generative model paper

### ISSUE THREAD

**Issue by Siddharth-Shrivastava7** [heejkoo/Awesome-Diffusion-Models#74]
Hi @heejkoo,

"Semantic Diffusion Network for Semantic Segmentation" is not technically a Diffusion based generative model paper. I think the title is a little misleading in some sense. 

If possible, you can check and can remove from the list.

Thanks!

**Comment by heejkoo** [comment]
Thanks!
