### ISSUE TITLE
Incorrect classification of paper "DocDiff: Document Enhancement via Residual Diffusion Models"

### ISSUE THREAD

**Issue by Royalvice** [heejkoo/Awesome-Diffusion-Models#81]
I’m delighted that our paper ‘DocDiff: Document Enhancement via Residual Diffusion Models’ has been included in this repository. However, there seems to be an issue with its classification. It should not be placed under the Natural Language category, but rather under Inverse Problems within the Vision category.

**Comment by heejkoo** [comment]
I am sorry for misclassification. I fixed it. Thank you.
