### ISSUE TITLE
Can you add our MICCAI 2023 paper?

### ISSUE THREAD

**Issue by xiaoiker** [heejkoo/Awesome-Diffusion-Models#82]
Hi, @heejkoo,

Thanks very much for your efforts in collecting these papers! I was wondering could you please add our recent diffusion paper for 3D Brain MRI generartion using 2D diffusion model?

Title: Generating Realistic 3D Brain MRIs Using a Conditional Diffusion Probabilistic Model
Authors: Wei Peng, Ehsan Adeli, Qingyu Zhao, Kilian M Pohl
Paper Link: https://arxiv.org/pdf/2212.08034
Code Link: https://github.com/Project-MONAI/GenerativeModels/tree/260-add-cdpm-model

Thanks a lot!

**Comment by heejkoo** [comment]
It is added. I am sorry for missing your paper!

**Comment by xiaoiker** [comment]
Thanks for your efforts and help!
