### ISSUE TITLE
it would be nice if you can put the website link in the description of the repo

### ISSUE THREAD

**Issue by yuanzhi-zhu** [heejkoo/Awesome-Diffusion-Models#83]
Thank you so much for this excellent repo you built!

Could you please add the link https://heejkoo.github.io/Awesome-Diffusion-Models/ to the About description in this repo? It will be very helpful.

here 
![image](https://github.com/heejkoo/Awesome-Diffusion-Models/assets/24802044/6f7006c1-8c7e-4be8-9d33-a0a17fffa692)

**Comment by heejkoo** [comment]
I did it, thank you for your advise!
