### ISSUE TITLE
Paper is about Diffusion MRI, not diffusion models

### ISSUE THREAD

**Issue by MathijsdeBoer** [heejkoo/Awesome-Diffusion-Models#85]
Under Segmentation, the following paper is listed:

Domain-agnostic segmentation of thalamic nuclei from joint structural and diffusion MRI
Henry F. J. Tregidgo et al. 2023

This work does not actually use a diffusion model, but a straightforward 3D U-Net to segment brain structures.
The confusion is probably caused by the concept of [Diffusion MRI](https://en.wikipedia.org/wiki/Diffusion_MRI). This sequence, simply put, tracks the direction and velocity of fluids (mostly water) moving around a given spatial location. Most often this is done in the brain as it's quite easy to keep in place with little to no patient movement. This lets you create these [cool looking fiber tractography images](https://en.wikipedia.org/wiki/Tractography), as fluid is more likely to move in parallel to the nerve bundles spread across your brain!

**Comment by heejkoo** [comment]
Thank you for letting me know and useful information. I removed it from the readme.md file!
